typography_spectrum: 0.6020632199943066
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5625
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.69207
analytics:
  google: null
  facebook: null
  twitter: null
name: Megacorp
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Back our Kickstarter Campaign!
    url: >-
      https://www.kickstarter.com/projects/megacorp/megacorp-the-cyberpunk-business-trading-card-game
    type: external
favicon: null
title: Megacorp Trading Card Game
purpose: []
